# Generated by Django 2.1.8 on 2019-11-06 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=32)),
                ('specification', models.TextField()),
                ('version', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('picture', models.ImageField(default='backstage/images/11.jpeg', upload_to='backstage/images')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backstage.CommodityType'),
        ),
    ]
