# Generated by Django 2.1.8 on 2019-11-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='version',
        ),
        migrations.AddField(
            model_name='commodity',
            name='picture',
            field=models.ImageField(default='backstage/image/11.jpeg', upload_to='backstage/images'),
        ),
    ]
