# Generated by Django 2.1.8 on 2019-11-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstage', '0002_auto_20191107_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
